version: '3'
services:
  route-finder:
    build: .
    volumes:
      - ./:/app
      - ./output:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
